### ISSUE TITLE
Set CI for building documentation as a website

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#1]
## Goal

Set up the CI to automatically generate library documentation as a website.

## Context

See #22. 

## Required features

- Use [sphinx](https://www.sphinx-doc.org/en/master/).
- The website should live in a separate branch of the project.
- Fail if a function is not documented (like R CMD check... maybe out of scope or part of #27?) 

## Specifications

- [ ] #49
- [ ] Add a badge indicating the status of the build.

## Out of scope

NA

## Related documents

NA

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/28

**Comment by gvegayoncdc** [comment]
@AFg6K7h4fhy2, @SamuelBrand1 added this link which is useful for the task: https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id5
