### ISSUE TITLE
Generation interval pmf

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#11]
## Goal

We want to have a single source of truth for the mathematical formulation of the generation interval probability mass function for flu and COVID. We want to be able to use this to immediately code up the math decided upon here. 

## Context

This was discussed in the 2024-02-27 meeting (see [minutes](https://github.com/cdcent/cfa-multisignal-renewal/tree/main/minutes)) and agreed upon in the [ADR record](https://github.com/cdcent/cfa-multisignal-renewal/tree/main/ADR/model) under `model_features.md`. This specific feature should be the same as what's implemented in the existing wastewater model. Completion of this task will allow us to implement the feature more quickly and should facilitate creation of a [model design document](https://github.com/cdcent/cfa-multisignal-renewal/blob/9b69f08e4def65e2a307885036167a0cc3667af7/model/vignettes/model.md). 

## Required features

- [x] #43
- [ ] sources for the underlying GI estimates for both diseases
- [ ] add to the feature to the [model design document ](https://github.com/cdcent/cfa-multisignal-renewal/blob/9b69f08e4def65e2a307885036167a0cc3667af7/model/vignettes/model.md)
- [ ] Include an independent test that checks TBD.
- [ ] Include documentation in the code using docstring

## Out of scope

- This does not include code, just specification of the feature in math/writing

## Related documents

- [Model feature prioritization](https://github.com/cdcent/cfa-multisignal-renewal/discussions/48)
- Existing wastewater [model definition](https://github.com/cdcent/cfa-forecast-renewal-ww/blob/main/model_definition.md)

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/72
author: @kaitejohnson

**Comment by gvegayoncdc** [comment]
Hey @SamuelBrand1, here is one you could take! I also suggest: #17!

**Comment by gvegayon** [comment]
Hey @SamuelBrand1, I know the issue says "[t]his does not include code, just specification of the feature in math/writing," but I would argue that it is a good idea to include coding. In my view, coding stuff helps with the thinking process of theory too, and it makes sense to include the coding and documentation at the same time. What do you think?

cc @dylanhmorris

**Comment by gvegayon** [comment]
As a reference to https://github.com/cdcent/cfa-multisignal-renewal/discussions/104#discussioncomment-9374461, this issue deals with the implementation of a stochastic generation interval (i.e. for inference). The GI used in the hospital admissions-only version of the WW project uses a deterministic quantity.

cc @kgostic

**Comment by kgostic** [comment]
Just to clarify about the generation interval: you're saying that for now, you're not going to try to estimate the GI in the model. Instead, you're just going to pass in a vector $\vec{v}$ where entries represent the probability mass of the discretized GI for integer delays of $d$ days.

If so, this is also how we're doing it in our $R_t$ model, so I think this is totally sufficient for now.
