### ISSUE TITLE
Review policy for PRs

### ISSUE THREAD

**Issue by seabbs** [CDCgov/multisignal-epi-inference#113]
Just looking for pointers towards the documentation around review standards in this project? I see some PRs with reviews, some without and some that are unlinked from issues. This is all likely fine but if not already worth writing up exactly what the expectations are.

_Looking again I see this is recent and so maybe due to staff absence? If so perhaps worth thinking about what  we should do to keep dev velocity up when critical staff take time out._

**Comment by gvegayon** [comment]
Good question, @seabbs! Yes, it has to do with dev speed. Since we don't have that many hands in this project, there are (were) some PRs that were directly merged without approval. For the moment, only PL and PSs can take that action (which is what happened).

**Comment by damonbayer** [comment]
Closed in https://github.com/CDCgov/multisignal-epi-inference/pull/224
