### ISSUE TITLE
Exponential growth model for initial infections

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#116]
## Goal

Implement the initialization of the infections using an exponential growth model as in the wastewater model (see [here](https://github.com/CDCgov/wastewater-informed-covid-forecasting/blob/61af2bbbd0cc179460b3b06c4fa209b3a50f6101/model_definition.md#renewal-process-for-incident-infections)):

> This process is initialized by estimating an initial exponential growth[^EpiNow2] of infections for 50 days prior to the calibration start time $t_0$:
> 
> $$ I(t) = I_0\exp(rt) $$
> 
> where $I_0$ is the initial per capita infection incident infections and $r$ is the exponential growth rate.

## Context

During discussions of feature prioritization. This particular component was not listed.

## Required features

The feature should be implemented as a `RandomVariable` object part of the `latent` submodule.

## Specifications

- [ ] Mathematical description of the component.
- [ ] Unit test evaluating the feature.
- [ ] Integration test with the basic model and hospital admissions model.
- [ ] Integration as part of a tutorial.

These specs may be moved to a different issue involving other components of the replication of the hospital admissions model in the wastewater project.

## Out of scope

- TBD

**Comment by gvegayon** [comment]
Hey @damonbayer, as we discussed, this could be implemeted via a latent process either extending the current implementation of the infections module or adding a new one called something like `latent.InfectionsWithExpGrowth(RandomVariable)`.

**Comment by damonbayer** [comment]
From my understanding, there are three key times related to this implementation:
* $t_0$: the time where the first latent infection(s) occur
* $t_{\text{seeded}}$: the time at which there is a sufficient infection history such that the renewal process can begin.
* $t_{\text{obs}}$: the time at which the first observation occurs.

I suppose there is no reason that $t_{\text{seeded}}$ couldn't be after $t_{\text{obs}}$, but I think it's appropriate to enforce $t_0 < t_{\text{seeded}} \leq t_{\text{obs}}$.

This issue relates to generating $I(t)$ for $t \in [t_0, t_{\text{seeded}}]$. In the current model, we have $I(t) = I_0$ for $t \in [t_0, t_{\text{seeded}}]$ and we only save $I(t)$ for $t \geq t_{\text{seeded}}$.

**When we have variation in $I(t)$ for $t \in [t_0, t_{\text{seeded}}]$, I assume we will want to keep track of all of these values. Is that correct?**

**Comment by gvegayon** [comment]
> When we have variation in [math] for [math], I assume we will want to keep track of all of these values. Is that correct?

Yes. Since the only sampled quantities in the equation are $I_0$ and $r$, the rest of the sequence is fully deterministic. You can use the `numpyro.deterministic` function to tag that and ask the model to keep track of it, e.g., 

https://github.com/CDCgov/multisignal-epi-inference/blob/a7d6d2d6cf453cfbfbb89c0389468e7d120bde8a/model/src/pyrenew/process/rtrandomwalk.py#L123

That said, I am not sure I'm following why we need $t_{seeded}$ and not only $t_0$ and $t_{obs}$. What am I missing?

**Comment by damonbayer** [comment]
$t_\text{seeded}$ corresponds to the idea of `padding` in the current hospitalization model tutorial (`example-with-datasets`).

In that model, we have $I(t) = I_0$ for $t \in [t_0, t_{\text{seeded}}]$. Then $I(t)$ follows the renewal process for $t > t_\text{seeded}$. The observations don't start until some time later, $t_\text{obs} = t_\text{seeded} +$ `padding`

**Comment by dylanhmorris** [comment]
I agree with @damonbayer; my only minor quibble is notational. Proposed default: let $t_0 = 0$ denote the first timepoint at which $I(t)$ is generated by the renewal process according to some $\mathcal{R}(t_0)$ (versus "seeded").

i.o.w. seeding times are by default negative: $t_\mathrm{firstseed} < t_0 = 0$
