### ISSUE TITLE
All `RandomVariable`s should be recorded (even if they are deterministic)

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#127]
## Goal

All `RandomVariable`s should be recorded, even if they are deterministic. Currently, when you use create a `DeterministicVariable`, that variable is not "recorded" (included in the MCMC output).

## Context
You could have one `HospitalAdmissionsModel` where the IHR is a non-deterministic `RandomVariable` and one where the IHR is deterministic. If the deterministic `RandomVariable` is not recorded, then the two models will have differently-shaped outputs and post processing (e.g., plotting standard figures) will be complicated.

**Comment by dylanhmorris** [comment]
My inclination here would be for `DeterministicVariable.sample()` to call `numpyro.deterministic()` under the hood, at least by default. Could potentially have a `track=False` or `record=False` setting to change that default behavior. 

https://github.com/CDCgov/multisignal-epi-inference/blob/d8727f1956363fd8759e0be6ff6aa55e639ceb38/model/src/pyrenew/deterministic/deterministic.py#L65-L84
