### ISSUE TITLE
Explore adding ArviZ dependency for diagnostics and visualization

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#139]
https://python.arviz.org/en/stable/

- [ ] Add examples using ArviZ to existing tutorials

**Comment by seabbs** [comment]
I think this is a great idea

**Comment by damonbayer** [comment]
This has been explored, and we have created https://github.com/CDCgov/multisignal-epi-inference/issues/200 and https://github.com/CDCgov/multisignal-epi-inference/issues/201.
