### ISSUE TITLE
Day-of-week effect

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#14]
## Goal

We want to have a single source of truth for the mathematical formulation of the day of week effect on the hospital admissions (and/or ED visits). We want to be able to use this to immediately code up the math decided upon here. 

## Context

This was discussed in the 2024-02-27 meeting (see [minutes](https://github.com/cdcent/cfa-multisignal-renewal/tree/main/minutes)) and agreed upon in the [ADR record](https://github.com/cdcent/cfa-multisignal-renewal/tree/main/ADR/model) under `model_features.md`. This specific feature should be the same as what's implemented in the existing wastewater model. Completion of this task will allow us to implement the feature more quickly and should facilitate creation of a [model design document](https://github.com/cdcent/cfa-multisignal-renewal/blob/9b69f08e4def65e2a307885036167a0cc3667af7/model/vignettes/model.md). 

## Required features

- [ ] mathematical description of the day of week effect applied to the hospital admissions and/or ED visit signals 
- [ ] add to the feature to the [model design document ](https://github.com/cdcent/cfa-multisignal-renewal/blob/9b69f08e4def65e2a307885036167a0cc3667af7/model/vignettes/model.md)
- [ ] Include an independent test that checks TBD.
- [ ] Include documentation in the code using docstring

## Out of scope

- This does not include code, just specification of the feature in math/writing

## Related documents

- [Model feature prioritization](https://github.com/cdcent/cfa-multisignal-renewal/discussions/48)
- Existing wastewater [model definition](https://github.com/cdcent/cfa-forecast-renewal-ww/blob/main/model_definition.md)

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/75
author: @kaitejohnson

**Comment by dylanhmorris** [comment]
> @dylanhmorris has some idea about implementing this with glmprediction, which he will comment today.

On reflection, I do not think this is the way to go for now. I think the most numerically stable and readable reimplementation of the existing model will frame this explicitly as sampling from the 7-simplex with the appropriate prior.

**Comment by gvegayon** [comment]
As @dylanhmorris suggests, I think the prior solves it. We can sample from a Dirichlet and use an affine transform to get there:

![image](https://github.com/CDCgov/multisignal-epi-inference/assets/893619/df8c886a-5aa1-45e3-b80e-921ce2b93cad)
