### ISSUE TITLE
Standardize output length for functions that yield sequences/timeseries

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#142]
> A number of array creation functions (deterministic or stochastic) exist in the project. I think we should standardize on any timeseries/sequence `sample(duration=n)` or `compute(duration=n)` call:
>
>- returning an array (which I'll call $y(t)$ ) of exactly length `n`. 
>- If $x \ge 1$ initial values are provided, including them as the first $x \le$ `n` entries in $y(t)$

_Originally posted by @dylanhmorris in https://github.com/CDCgov/multisignal-epi-inference/pull/131#discussion_r1621392498_

**Comment by dylanhmorris** [comment]
@gvegayon @damonbayer @AFg6K7h4fhy2 for visibility? Thoughts on this proposed standard or counterproposals?

**Comment by gvegayon** [comment]
#143 (to be merged into #131) addresses this.

**Comment by gvegayon** [comment]
The main PR dealing with this was merged. Closing.
