### ISSUE TITLE
Remove default seed value from `run`

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#146]
If we want people to be able to call run without explicitly specifying a seed, perhaps generate a (pseudo) random one if `rng_key` is `None`?
https://github.com/CDCgov/multisignal-epi-inference/blob/b3337c1ca0e8c06027c84bd401c0735fd60c46cf/model/src/pyrenew/metaclass.py#L312

**Comment by gvegayon** [comment]
That has been my approach in the past.
