### ISSUE TITLE
Create forecasting interface

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#169]
## Goal

We should have a consistent interface for creating forecasts from models.

## Context

For implementation inspiration, we can look at the [NumPyro Time Series Forecasting](https://num.pyro.ai/en/latest/tutorials/time_series_forecasting.html) example.

**Comment by SamuelBrand1** [comment]
Following from f2f discussion, its worth considering this problem: https://github.com/CDCgov/Rt-without-renewal/issues/243

Underlying difficulty is using [`Predictive`](https://num.pyro.ai/en/stable/utilities.html#numpyro.infer.util.Predictive), you should check if it works on an AR process like here https://num.pyro.ai/en/latest/examples/ar2.html because its a different inference process (stochastic even when conditioned on parameters).

**Comment by damonbayer** [comment]
There is some discussion of forecasting for the AR2 NumPyro demo here: https://github.com/pyro-ppl/numpyro/pull/1350

**Comment by damonbayer** [comment]
See also https://juanitorduz.github.io/arma_numpyro/

**Comment by SamuelBrand1** [comment]
> See also https://juanitorduz.github.io/arma_numpyro/

This is nice example... but looks a bit weird? 

I think `statsmodel` use [MLE inference](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima.model.ARIMA.fit.html#statsmodels.tsa.arima.model.ARIMA.fit) under the hood? In which case I'm not sure I'd expect the forecast to look so similar to one fitted with NUTS?

**Comment by damonbayer** [comment]
@SamuelBrand1 weird in what way?

**Comment by SamuelBrand1** [comment]
That it looks so similar to statsmodel given its a different inference method? It doesn't look like the posteriors are super peaked?

**Comment by SamuelBrand1** [comment]
Looking at the code, the predictive mode switch looks like it makes sense.

**Comment by damonbayer** [comment]
Does anyone have a forecasting interface that they really like that I might use for inspiration? Could by in Python, R, Julia, etc. @SamuelBrand1 @seabbs @dylanhmorris

**Comment by damonbayer** [comment]
This [discussion on the numpyro forum](https://forum.pyro.ai/t/forecasting-with-a-stochastic-volatility-model-in-numpyro/3451/15) looks promising.

Also noting that there is a [`GaussianRandomWalk`](https://num.pyro.ai/en/stable/distributions.html#gaussianrandomwalk) class built in to numpyro that we could take inspiration from.

**Comment by SamuelBrand1** [comment]
> This [discussion on the numpyro forum](https://forum.pyro.ai/t/forecasting-with-a-stochastic-volatility-model-in-numpyro/3451/15) looks promising.

Yeah, this example points at what I was worried about with forecasting (i.e. when you have a stochastic distribution in the future as opposed to the time series example with `numpyro` docs). 

From my basic looking around it seems that the most common solution in `numpyro` land is to have some kind of conditional statement inside the `def` of the sampleable model... that seems to do the job but maybe seems like potentially a lot of boiler plate? E.g. would we get pushed towards needing to write an extra conditional chunk of _all_ the models at the top level that we want to forecast from?

**Comment by SamuelBrand1** [comment]
> Also noting that there is a [`GaussianRandomWalk`](https://num.pyro.ai/en/stable/distributions.html#gaussianrandomwalk) class built in to numpyro that we could take inspiration from.

Is there a downside to just importing it? If its been provided by numpyro devs then it might be better in some way that what we do ourselves?

**Comment by SamuelBrand1** [comment]
> Does anyone have a forecasting interface (i.e. the function signature for creating a forecast) that they really like that I might use for inspiration? Could be in Python, R, Julia, etc. @SamuelBrand1 @seabbs @dylanhmorris

I like the `epidemia` interface for prediction/counterfactual: https://imperialcollegelondon.github.io/epidemia/reference/posterior_predict.epimodel.html .

The tl; dr explanation is they fit an object (which contains posterior draws for the params) and then passing `newdata` can create forecasts (by being longer) and/or counterfactuals (by having different covariates like an earlier lockdown). Its demoed here, https://imperialcollegelondon.github.io/epidemia/articles/europe-covid.html .
