### ISSUE TITLE
Latest version of filelock breaks CI

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#181]
It seems that the latest version of filelock (which was [updated ~20 mins](https://pypi.org/project/filelock/3.15.0/) ago since this post) is buggy. The CI of #158 fails as well as running other CIs that were previously working. Filelock went from 3.14.0 to 3.15.0. Here is [the CI run that worked OK](https://github.com/CDCgov/multisignal-epi-inference/actions/runs/9486888984/job/26142261225#step:5:59):

![image](https://github.com/CDCgov/multisignal-epi-inference/assets/893619/f6c255e4-d95e-4bae-a555-f8fb14a6434b)

Here is [the one that is not working](https://github.com/CDCgov/multisignal-epi-inference/actions/runs/9486888984/job/26144674834#step:5:59):

![image](https://github.com/CDCgov/multisignal-epi-inference/assets/893619/0ebb148a-c755-45ea-a4d8-e5f0875714cd)

I suggest forcing the old version (for now) so that we can continue developing without issues.

cc @gaborbernat

**Comment by gvegayon** [comment]
Also reported [here](https://github.com/tox-dev/filelock/issues/337)

**Comment by damonbayer** [comment]
Most recent version was yanked. Should be fixed soon automatically.
