### ISSUE TITLE
Prioritization of model features

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#2]
We need to identify: (a) what are these specifically, (b) how we prioritize them. These have been mentioned a few times, but we need to ensure we have a clear path for development. Here is a list of features that have been mentioned before:

1.  **Granularity**: "[I]ntegrate other more geographically granular data signals even in the absence of a state or national signal at all" (https://github.com/cdcent/cfa-multisignal-renewal/discussions/2#discussioncomment-8317531).

2.  **Multisignal fusion**: Add arbitrary signals (vs hard-code them) using the same mechanism as in the WW model (https://github.com/cdcent/cfa-multisignal-renewal/discussions/2#discussioncomment-8318600).

3. **Arbitrary hierarchy**: "[C]hange the hierarchical structure really easily depending on the availability of signals and how one wants to set up the hierarchy" (https://github.com/cdcent/cfa-multisignal-renewal/discussions/2#discussioncomment-8318848)

4. **Rt DGP**: AR and Gaussian process for Rt (https://github.com/cdcent/cfa-stf-team-materials/discussions/21#discussion-6051731)

5. **Reporting delay DGP** Hazard model (https://github.com/cdcent/cfa-stf-team-materials/discussions/21#discussioncomment-8082682)

7. **Rt granularity**: Daily instead of weekly Rt (https://github.com/cdcent/cfa-stf-team-materials/discussions/21#discussioncomment-8082682)

For each one of these, we need to define the following:

- **Priority**
    - Must have
    - Nice to have
- **Complexity**
    - High (Re-factor+design existing code)
    - Medium (add a new class/extend function)
    - Low (twitch a few lines of code).
- **When**
    - 2024-06-14 Working model prototype
    - Other?

## More information

- Discussed in https://github.com/cdcent/cfa-multisignal-renewal/discussions/2.
- Project milestones #36.
- Math details #18. 

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/42

**Comment by damonbayer** [comment]
Suggest moving this to an actual discussion if we want to continue discussing: https://github.com/CDCgov/multisignal-epi-inference/discussions
