### ISSUE TITLE
Create methods for simulating from prior and predictive distributions

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#202]
Pre-requisite to https://github.com/CDCgov/multisignal-epi-inference/issues/169.

Model class should have `model.sample_prior()` and `model.predict(samples)` methods.

**Comment by AFg6K7h4fhy2** [comment]
This was mentioned in Teams.

> Did you have an (eventual) solution in mind beyond kwargs? I feel it works well for what we have now but might change in the future if there is something better.

Response:

> It would be nice if you didn’t have to pass any arguments at all. I would want to somehow differentiate between a model and a model with data.
