### ISSUE TITLE
Separate pipeline from pyrenew

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#208]
At this point, I think separating the pipeline from pyrenew only amounts to removing the nearly-empty `pipeline` folder and references to it in the `readme`s.

**Comment by AFg6K7h4fhy2** [comment]
Once the pipeline-description content is moved out of `pipeline`, do you have a vision for a more substantial `pipeline` folder (one that would make sense to have) to eventually exist, or do you see this been a lasting move to discontinue the `pipeline` folder?

**Comment by damonbayer** [comment]
I made this issue with the intention of removing the pipeline folder and eventually putting the pipeline in a separate repository, but I'm not completely committed to that plan. Regardless, we have no pipeline at the moment, so I don't see the point of having a pipeline folder.

**Comment by AFg6K7h4fhy2** [comment]
> so I don't see the point of having a pipeline folder

Agree, for now.

> but I'm not completely committed to that plan

There is probably a better way but something akin to what you have mentioned seems good.

**Comment by damonbayer** [comment]
Additional context: it now seems like there will be multiple models (Flu and Covid) using PyRenew, so I think those should probably be separate projects / repos. Having both those pipelines and the package code all in one repo seems messy.
