### ISSUE TITLE
Alternative to Jupyter notebooks

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#22]
## Goal

Have a lighter version of jupyter notebook that shows the raw python code without too much around it (i.e., large json files).

## Context

Small changes in the code embeded in jupyter notebooks can lead to big changes in the jupyter files, inflating the number of changes tracked by git.

## Required features

TBA

## Specifications

TBA

## Out of scope

TBA

## Related documents

- See #https://github.com/cdcent/cfa-multisignal-renewal/pull/87#discussion_r1511547834

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/88
author: @gvegayoncdc

**Comment by gvegayoncdc** [comment]
@natemcintosh and @AFg6K7h4fhy2

**Comment by natemcintosh** [comment]
I would say Quarto would be a good option here. Probably more widely spread than marimo (as much as I'd like to try it) with better support for many output formats

**Comment by gvegayoncdc** [comment]
As we discussed during the daily, we will proceed with quarto for the moment. The issue will be kept open while we test quarto and think about alternatives for this. One mentioned by @dylanhmorris is https://sphinx-gallery.github.io/.
