### ISSUE TITLE
Example numpyro models

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#23]
As suggested by @seabbs, here is an issue for posting and discussing other Numpyro-based projects and what we can learn from them.

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/92
author: @dylanhmorris 

---

# Ramsey
- JAX/Numpyro compatible implementations of stochastic processes encountered in machine learning
- Github: https://github.com/ramsey-devs/ramsey
- Docs: https://ramsey.readthedocs.io/en/latest/

---

# exojax
- Application of Jax/Numpyro to astrophysics. Looks like a fairly mature project
- github: https://github.com/HajimeKawahara/exojax
- docs: https://secondearths.sakura.ne.jp/exojax

**Comment by damonbayer** [comment]
Propose moving this to a discussion if it is still desired https://github.com/CDCgov/multisignal-epi-inference/discussions
