### ISSUE TITLE
Move tutorials in `./model/docs/` to `./docs/source/tutorials`

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#232]
> 1. Do we want to move the tutorials to the `./docs` folder instead? I've been thinking about this for a while now, and I believe it makes sense to keep all documentation in the same place.

Yes. We should do this.

_Originally posted by @damonbayer in https://github.com/CDCgov/multisignal-epi-inference/issues/224#issuecomment-2200413117_

**Comment by damonbayer** [comment]
@gvegayon Can you do this in its own PR (separate from https://github.com/CDCgov/multisignal-epi-inference/pull/224)? I thin it is out of scope for that PR and will best to merge ASAP.

**Comment by gvegayon** [comment]
No worries, @damonbayer. It is now on its own.
