### ISSUE TITLE
Write a notebook demostrating pyrenew

### ISSUE THREAD

**Issue by gvegayoncdc** [CDCgov/multisignal-epi-inference#24]
## Goal

Have a start-to-finish demo of `pyrenew` showcasing the library's main features.

## Context

During porting from CDCent we realized the original demo notebook featured files not available in the repo.

## Required features

- Jupyter notebook with the code.
- It should show an example simulating a renewal model using one of the classes included in the library.

## Specifications

- [ ] The notebook can be built automatically when the site builds (see #1)
- [ ] It should include simulated data for a 'model fitting' example.

## Out of scope

None

## Related documents

See original code on CDCent.

cc @dylanhmorris

**Comment by dylanhmorris** [comment]
Closed by #3
