### ISSUE TITLE
Light refactor of models based on experience with Predictive, forecasting, and plans for time handling.

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#249]
- [ ] `n_timepoints_to_simulate` should be renamed. Maybe just `n_datapoints`
- [x] We should not pad data inside or outside of the model. Right now we pad and then slice when we could just do neither. Addressed in https://github.com/CDCgov/multisignal-epi-inference/pull/241
- [x] There should not be a separate fork `if observed_data is None` in either model Addressed in https://github.com/CDCgov/multisignal-epi-inference/pull/241

**Comment by gvegayon** [comment]
In the context of #304, I realized we have the arguments `n_timepoints` and `duration` for seeding processes and processes in general. Shouldn't all be named `duration`, @damonbayer @dylanhmorris?

**Comment by damonbayer** [comment]
> Shouldn't all be named `duration`, @damonbayer @dylanhmorris?

In https://github.com/CDCgov/multisignal-epi-inference/issues/156, we standardized on `n_timepoints`, but I think we should do something with time units for these arguments.

**Comment by dylanhmorris** [comment]
New issue to discuss/decide this?
