### ISSUE TITLE
Accommodate warning for multi-chain sampling in tutorials

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#254]
Several tutorials feature this warning:
```
/home/runner/work/multisignal-epi-inference/multisignal-epi-inference/model/src/pyrenew/metaclass.py:389: UserWarning: There are not enough devices to run parallel chains: expected 2 but got 1. Chains will be drawn sequentially. If you are running MCMC in CPU, consider using `numpyro.set_host_device_count(2)` at the beginning of your program. You can double-check how many devices are available in your system using `jax.local_device_count()`.
  self.mcmc = MCMC(
```
_Originally posted by @damonbayer in https://github.com/CDCgov/multisignal-epi-inference/pull/234#pullrequestreview-2164303445_
            

We should either silence it or perform sampling in parallel.

**Comment by sbidari** [comment]
The default `chain_method` in numpyro is "parallel". I added `chain_method="sequential"` to avoid it in the tutorial. I will change this wherever we sample more than one chain.
