### ISSUE TITLE
Standardize default `eps` values for count RVs across the package

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#268]
Right now there is variation:

https://github.com/CDCgov/multisignal-epi-inference/blob/fb8a8a493a86e733750d05f9102262178b35357c/model/src/pyrenew/observation/poisson.py#L20

https://github.com/CDCgov/multisignal-epi-inference/blob/fb8a8a493a86e733750d05f9102262178b35357c/model/src/pyrenew/observation/negativebinomial.py#L22

Should arguably do something dynamic using `jnp.finfo`, and should be the same thing packagewide.

**Comment by dylanhmorris** [comment]
@damonbayer any thoughts?

**Comment by damonbayer** [comment]
> @damonbayer any thoughts?

It doesn't look like we have any tests related to this. I think we should start by documenting when the naive implementation fails and writing a test based on that.

**Comment by AFg6K7h4fhy2** [comment]
Assigning myself to this; others feel free to join if I'm not getting it done in as timely enough a fashion as desired.
