### ISSUE TITLE
fix image rendering in the website

### ISSUE THREAD

**Issue by sbidari** [CDCgov/multisignal-epi-inference#271]
Quarto doesn't like when a code cell results in multiple outputs. This could be prevented by adding a semi-colon at the end of the code line or using `plt.show()`

Related discussion: 

              > edit: I realize that the addition of `plot.show()` is totally unrelated to the issue in this PR and probably would have been better as it's own PR. I noticed the images were not rendering properly while I was working on this and fixed it.

Interesting. Please create new issue and/or PR to describe and fix this problem.

_Originally posted by @damonbayer in https://github.com/CDCgov/multisignal-epi-inference/issues/270#issuecomment-2231952666_

**Comment by damonbayer** [comment]
I haven't noticed this problem before. Can you elaborate on "doesn't like?" A screenshot might be helpful.

**Comment by sbidari** [comment]
Here is a screenshot from the website. 

![Capture](https://github.com/user-attachments/assets/cdc527cb-e5f2-4732-9d63-f2b389aa456b)

I also get the following error locally while rendering the qmd file 
```{bash}Error running filter /opt/quarto/share/filters/main.lua:
Block, list of Blocks, or compatible element expected, got table
        while retrieving function argument blocks
        while retrieving arguments for function Blocks
```

**Comment by damonbayer** [comment]
Thanks. That's bad! Not sure how we missed it.

**Comment by sbidari** [comment]
> Screenshots are from `basic_renewal_model`, I believe.

Yes, the hospital admissions tutorials renders well.
