### ISSUE TITLE
Streamline `hospital_admissions_model` tutorial?

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#273]
The `hospital_admissions_model` tutorial is getting a bit long and, with https://github.com/CDCgov/multisignal-epi-inference/pull/267 merged, it takes quite a while for all of the inference to finish. We should consider removing some parts.

**Comment by dylanhmorris** [comment]
Some of the slow inference is folk theorem, as discussed in #267, but there is also some conceptual duplication. Will propose fixes to both.
