### ISSUE TITLE
Re-use simple Rt definition throughout testing suite

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#287]
see e.g.:

> Should we share this across multiple files?

_Originally posted by @damonbayer in https://github.com/CDCgov/multisignal-epi-inference/pull/275#discussion_r1685019213_

**Comment by sbidari** [comment]
what is DRY?

**Comment by dylanhmorris** [comment]
Stands for ["don't repeat yourself"](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
