### ISSUE TITLE
Remove #! from non-executable files

### ISSUE THREAD

**Issue by ekr-cfa** [CDCgov/multisignal-epi-inference#29]
I see that a number of the `.py` files start with  `#!/usr/bin/env/python`, as in:

https://github.com/CDCgov/multisignal-epi-inference/blob/main/model/src/pyrenew/basic.py#L1

These are only needed when you will be executing the file directly, because their purpose is to tell the shell which interpreter to run. I.e., so you can do `./foo.py` rather than `python foo.py`. However, if the python code is just a module that isn't intended to be run but just imported, then you don't need this.

In addition, this is actually the wrong line, because what's after the `#!` needs to be something executable, but this isn't usually a valid path, because `/usr/bin/env` is a program, not a directory. Rather, you want `/usr/bin/env python`, which runs the `env` command to run `python`.

**Comment by gvegayoncdc** [comment]
Thanks for flagging that, @ekr-cfa. @dylanhmorris, I can address this on #26.
