### ISSUE TITLE
Remove `pyrenew_demo.qmd`

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#290]
It is no longer part of the website but it remains in the tutorials source. It should be removed (or, if parts are essential, edited to be non-redundant with other tutorials and reintroduced).

**Comment by damonbayer** [comment]
I believe it was intended to be removed in https://github.com/CDCgov/multisignal-epi-inference/pull/191#issuecomment-2214230164 @sbidari can you confirm?

**Comment by sbidari** [comment]
Confirming `pyrenew_demo.qmd` was to be removed. Will remove it now
