### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#31]
## Goal

Fill the gaps. There's a lot of undocumented code. We need to make sure that it as the minimum: (a) Title, (b) brief description, (c) `Parameters`, and (d) `Returns` (tag).

## Context

[Short paragraph describing how the issue arose and constraints imposed by the existing code architecture]

## Specifications

Here is the list of currently undocumented functions/modules:

- [ ] TBD

## Out of scope

- Add mathematical equations/definitions. That is needed but won't be approached here.

## Related documents

**Comment by gvegayon** [comment]
This is now #47
