### ISSUE TITLE
Simplify all uses of random rng keys

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#310]
This was started in https://github.com/CDCgov/multisignal-epi-inference/pull/275.

Throughout the codebase, we have code like 

```python
np.random.seed(223)
with numpyro.handlers.seed(rng_seed=np.random.randint(1, 60)):
    model.sample()
```

This is just as "random" as

```python
with numpyro.handlers.seed(rng_seed=223):
    model.sample()
```

but the latter is more readable.

**Comment by AFg6K7h4fhy2** [comment]
Pointing out to @sbidari that this currently has a PR (#317)
