### ISSUE TITLE
Review implementation of DeterministicProcess

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#311]
> I'd also suggest reviewing the implementation here. I think given some other choices we've made we'll perhaps want to modify it. Out of scope for this PR, however.

_Originally posted by @dylanhmorris in https://github.com/CDCgov/multisignal-epi-inference/pull/262#discussion_r1690473342_

**Comment by damonbayer** [comment]
Closing in favor of https://github.com/CDCgov/multisignal-epi-inference/issues/335

**Comment by damonbayer** [comment]
Closing in favor of https://github.com/CDCgov/multisignal-epi-inference/issues/335
