### ISSUE TITLE
Rename the `vars` attribute of `DeterministicVariable` to `value`

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#326]
This will make it more consistent with `SampledValue`, and indeed allow for creating new `DeterministicVariable` instances by unpacking `SampledValue` instances (see https://github.com/CDCgov/multisignal-epi-inference/pull/262#discussion_r1690441825)

**Comment by AFg6K7h4fhy2** [comment]
I can do this in #324

**Comment by dylanhmorris** [comment]
I think this should be a separate PR given that there may be references to the `vars` attribute in parts of the codebase not affected by the constructor argument reordering. Happy for you to tackle it though if you are willing, @AFg6K7h4fhy2

**Comment by AFg6K7h4fhy2** [comment]
I am willing. I've unlinked the previous branch and made a new one.

**Comment by AFg6K7h4fhy2** [comment]
I think having the aforementioned PR, i.e. 324, reviewed and submitted would be good before I create a PR with changes for this issue.

**Comment by dylanhmorris** [comment]
Reviewing #324 now.
