### ISSUE TITLE
Define a narrow `test` set of poetry dependencies and run CI testing in that context

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#337]
This will catch dependency problems that can be obscured when running in a general `dev` context, see e.g. #336

**Comment by dylanhmorris** [comment]
@CDCgov/multisignal-epi-inference-devs for awareness

**Comment by sbidari** [comment]
To be sure, this would mean creating a dependency group in `pyproject.toml` for running tests in CI? @dylanhmorris

**Comment by dylanhmorris** [comment]
Yes. I would suggest splitting the `dev` dependency group into a `docs` group and a `test` group. I think that should cover all of what's currently in `dev`, but if not we can thinking about what the other group(s) should be called
