### ISSUE TITLE
possible bug in `_assert_sample_and_rtype`?

### ISSUE THREAD

**Issue by sbidari** [CDCgov/multisignal-epi-inference#340]
I also noticed `_assert_sample_and_rtype` only asserts that the return type **annotation** is a `tuple` (or `namedtuple`) but not the sample **return** which makes me think maybe this was not intended.  Hoping to get clarification on this.
For example, the below runs without errors:

```{python}
from pyrenew.metaclass import RandomVariable, _assert_sample_and_rtype

class RVreturnNonTuple(RandomVariable):
    """
    Class for a RandomVariable with
    sample value 1
    """

    def sample(self, **kwargs) -> tuple:
        """
        Deterministic sampling method that returns 1
        """
        return 1

    def validate(self):

        return None
    
    
rv5 = RVreturnNonTuple()
_assert_sample_and_rtype(rv5)
```

**Comment by dylanhmorris** [comment]
Thanks @sbidari. Would be good to get @gvegayon's thoughts here I think.

**Comment by damonbayer** [comment]
I think this test should have been changed in https://github.com/CDCgov/multisignal-epi-inference/pull/262. We now expect all `RandomVariables` to return tuples (eventually named tuples) of `SampledValue`s

**Comment by gvegayon** [comment]
I'm not completely following @sbidari. The function checks for annotations only and avoids calling the sample function intentionally. In principle, we can test return types by calling the sample method, but if it depends on parameters and or pseudo RNG, it becomes more case-specific. Furthermore, often checking types on jax arrays can be tricky as they jax uses tracers instead (leveraging duck typing).

**Comment by sbidari** [comment]
Thanks for the clarification @gvegayon. My question was if checking only the annotation was intentional and it now makes sense why. 
 
Closing this issue as completed!
