### ISSUE TITLE
DRYify testing of validation errors

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#345]
> We have this type of check/error message throughout the project. Could be good to write a function for it.

_Originally posted by @damonbayer in https://github.com/CDCgov/multisignal-epi-inference/pull/342#discussion_r1697286580_

**Comment by sbidari** [comment]
What would this function look like given the error message for `ValueError` is different in each instance?

**Comment by damonbayer** [comment]
Something like

```python
def helpful_type_assertion(value, expected_type, arg_name, context):
    if not isinstance(value, expected_type):
        raise TypeError(f"{arg_name} passed to {context} is expected to be {expected_type}. Got {value} with type {type(value)}")
```
