### ISSUE TITLE
Standards In Plotting For Inference & Forecasting Output

### ISSUE THREAD

**Issue by O957** [CDCgov/multisignal-epi-inference#381]
Presently, `Model`s in `metaclass.py` have a method called `plot_posterior`, which calls `plot_posterior` located in `mcmcutils.py`. The tutorial [Fitting a hospital admissions-only model](https://cdcgov.github.io/multisignal-epi-inference/tutorials/hospital_admissions_model.html) employs `arviz` cohesively throughout, and in previous discussions, MSR developers seemed to converge on using `arviz` abundantly. 

Should `Model` be made to have additional plotting features, such as [plot_trace](https://python.arviz.org/en/stable/examples/plot_trace.html) or [plot_ppc](https://python.arviz.org/en/stable/examples/plot_ppc.html) from `arviz`? If not, then can we develop some standards for what to plot after retrieving samples from our MSR models?

**Comment by damonbayer** [comment]
Agree in general that there should be support for more convenient plotting. If we go this direction, I think we should start with more support for converting model output to ArviZ [InferenceData](https://python.arviz.org/en/stable/api/inference_data.html).

**Comment by AFg6K7h4fhy2** [comment]
> Agree in general that there should be support for more convenient plotting. If we go this direction, I think we should start with more support for converting model output to ArviZ [InferenceData](https://python.arviz.org/en/stable/api/inference_data.html).

Wrt your latter remark, I agree. I spent some time playing around with InferenceData because trace, HDI, and ppc plots are easier to use this way, but didn't get as far as I would like. Expected value for our inference / forecasting pipelines from really understanding `arviz` seems high. Hopefully #135 can demonstrate some `arviz` utilities not previously demonstrated.
