### ISSUE TITLE
Set Up CDCGov Repository For `cfaepim`-MSR

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [CDCgov/multisignal-epi-inference#382]
At present, #135 has not been merged (this would entail the removal of many files on the basis that MSR is not the correct place for them) and is overlapping greatly with #359 in the sense that the author of this issue is writing plotting and hypothesis testing code (KS test) to evaluate `cfaepim`-MSR relative to `cfaepim`. 

As has been briefly discussed between the author and @dylanhmorris, beyond a certain level of development, models constructed via MSR might be better contained within their own repositories. I believe that @damonbayer is roughly in agreement with this, possibly conditional on other checks being met. 

Since DHM suggested this process of re-housing `cfaepim`-MSR be deferred until further evaluation work has been done, the author will not move forward with the hasty completion of this issue; rather, the issue exists as a placeholder for a task that will, in the near future, need to be done.

**Comment by damonbayer** [comment]
We should discuss names for this and the PyRenew-based wastewater repo.

**Comment by AFg6K7h4fhy2** [comment]
Noting here, since record only currently exists elsewhere, that the model in #313 will be given its own repository first before `cfaepim`-MSR is given its own repository.

**Comment by damonbayer** [comment]
Repo requested: https://github.com/cdcent/cfa-predict-github-repos-meta/issues/17

**Comment by damonbayer** [comment]
Repo exists: https://github.com/CDCgov/pyrenew-flu-light
