### ISSUE TITLE
Porting weekly model from CDC ent

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#52]
## Goal

Port [model from CDCent](https://github.com/cdcent/cfa-multisignal-renewal/compare/main...dylanhmorris/replicate-epimlight)

## Context

This model was identified during branch pruning of the CDCent side.

## Specifications

- [ ] Code matches `Model` and `RandomVariable` metaclasses
- [ ] Code is properly documented using numpy's style.
- [ ] Code is properly tested.

**Comment by damonbayer** [comment]
I think this is done or no longer needed. Feel free to reopen if I am wrong @dylanhmorris @gvegayon
