### ISSUE TITLE
What arguments should *.sample() have?

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#53]
As flagged in https://github.com/CDCgov/multisignal-epi-inference/pull/39#discussion_r1546628941, we may want to change the current template of `(RandomVariable|Model).sample()` from `sample(random_variables, constants)` to `sample(**kwargs)`. This issue is to discuss this proposed change. It may lead to a development PR.

cc @dylanhmorris @AFg6K7h4fhy2 @SamuelBrand1 @cshelley

**Comment by dylanhmorris** [comment]
I vote for individual instances to have named arguments, e.g.

```python
class Infections(Random Variable):

    <other functions>

    def sample(self, 
                      Rt: ArrayLike = None, 
                      gen_int: DiscretePMF = None,
                     **kwargs):
```

I think this will balance extensibility and readability. I like that one can either do:

```Python
inf = Infections()
inf.sample(Rt = some_Rt, gen_int = some_gen_int)
```

or
```
inf = Infections
rand_vars = {
    "Rt": some_Rt,
    "gen_int": some_gen_int,
    "other_variable": some_other_variable
}
inf.sample(**rand_vars)

**Comment by gvegayon** [comment]
I wonder if it would be good to have an alternative (e.g., a decorator) that wraps the sample function to recover the old functionality, i.e., pass arguments via two dictionaries. Can decorators be used to wrap functions without replacing them? Anyways, I'm inclined to the `**kwargs`.

**Comment by dylanhmorris** [comment]
I mean the beauty of dictionary unpacking is that 

```
inf.sample(**random_variables, **constants)
```

should work out of the box provided all the needed arguments are defined.

**Comment by gvegayon** [comment]
I see one small problem:

- In `RtInfectionRenewalModel`, `latent_infections` can be anything, so that's good.
- Under the hood, the model passes `Rt` to the `latent_infections` via unpacking, but it also passes `random_variables` passed during the call to the `RtInfectionRenewal.sample()` function:
  ```python
  latent, *_ = self.sample_infections_latent(
    random_variables={**random_variables, **dict(Rt=Rt)},
    constants=constants,
  )
  ```

The problem: If we go with the `**kwargs` route, we would still have to anticipate all variable names needed to be passed to each function. So, if `latent_infections` needed to receive an optional argument, we would need to include that argument on the call to  `RtInfectionRenewal.sample()`, which is what we wanted to avoid in the first place.

A potential fix: Have all `sample()` methods explicitly include `**kwargs`. The new code would look something like this:


```python
class RtInfectionRenewal(RandomVariable):

  ...

  def sample(self, **kwargs):

    ...

    latent, *_ = self.sample_infections_latent({**kwargs, **dict(Rt=Rt)})
```

What do you think?

**Comment by gvegayon** [comment]
Or... from what I read you, this should also work:

```python
latent, *_ = self.sample_infections_latent(**kwargs, Rt=Rt)
```

No?

**Comment by gvegayon** [comment]
OK, so after today's daily, the pattern we'll be following is:

- Use named arguments + `**kwargs`.
- `**kwargs` should always be passed on.
- We should never use `kwargs` as dictionaries, i.e., use the `.get()` method; that'd be like what we are doing right now, which we don't like.

I'm closing this issue to start a new one for refactoring code.
