### ISSUE TITLE
Expansion of ArrayLike and others in sphinx docs

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#54]
Currently, sphinx's expansion of types is ugly (and excessive):

![image](https://github.com/CDCgov/multisignal-epi-inference/assets/893619/95ad8526-8a50-479e-8502-9895036ed176)

A solution is to change the configuration as [shown here](https://stackoverflow.com/a/75039576/2097171). It should be an easy fix.

**Comment by dylanhmorris** [comment]
@AFg6K7h4fhy2 can you make this configuration change and confirm it resolves the issue?
