### ISSUE TITLE
Get Azure login GitHub action working

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#6]
## Goal

Create a new github action that logs into Azure, and prints out something simple to show that it is working.

## Context

Getting Azure Github Actions working for this project will significantly improve our ability to automate testing on Azure. This issue is the first step towards that goal. See the [Azure/login](https://github.com/Azure/login) action.

@jkislin is assisting us getting the new credentials, and into the repo.

## Required features

- Create a new workflow file that logs into Azure
- Add the necessary secrets to this repo's actions secrets

## Specifications

- [x] Create the new workflow file, ideally as small and simple as possible
- [ ] Receive new secrets
- [ ] Put new secrets in the repo's actions secrets.

## Out of scope

- Anything beyond just getting logged in

## Related documents

- An [example](https://github.com/cdcent/cfa_vap_autoconfig/blob/7fd9dad40f1dfc93e3f0bff8466f4f66283999e7/.github/workflows/update_vap_wsl_image.yml#L67-L110) of using the Azure login for the VAP WSL
- The [examples](https://github.com/marketplace/actions/azure-login#workflow-examples) on the [Azure/login](https://github.com/Azure/login) page.

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/60
author: @natemcintosh

**Comment by gvegayoncdc** [comment]
@natemcintosh, this article is very relevant for GHA + Azure: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections.

**Comment by gvegayoncdc** [comment]
This is also key, @natemcintosh: https://msrc.microsoft.com/blog/2023/11/microsoft-guidance-regarding-credentials-leaked-to-github-actions-logs-through-azure-cli/
