### ISSUE TITLE
Repo discoverability

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#69]
## Goal

The structure of this repository and goals of this project should be understandable to a new team member and, ideally, the public.

## Context

As a new team member, I am finding it difficult to grok the repo / project. A few sentences in the readme and installation instructions (for both contributors and users) would go a long way.

Some questions I had that could be addressed:
* What is the purpose of this project and who is the intended audience?
* What does it mean that it is an _internal_ forecasting model?
* Does this repo contain "a model" as is stated in the readme? Or is it a library for creating models? Or a specific implementation of a model?
* According to the readme, the project has two main folders - `model` and `pipeline`. What's in those folders and how do they relate?
* What is `PyRenew`? How do I install it (current installation instructions point to an archived GitHub repo)? Why isn't it mentioned in the root readme?
* The `pipeline` directory is blank. What is it going to be used for?

**Comment by gvegayon** [comment]
Thanks, @damonbayer! This is something I have thought about before. We need a better `README.md` to welcome users, and we can start adding documentation for new team members under `docs`. Both @cshelley and @AFg6K7h4fhy2 have some material that could be added as a section of the website living under `docs`.

**Comment by damonbayer** [comment]
Addressed in https://github.com/CDCgov/multisignal-epi-inference/pull/118
