### ISSUE TITLE
Outline Needs for Developer Documentation

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#7]
The idea is to add on the README.md file some resources for new member teams who are not familiar with the renewal models. Details TBD.

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/33
author: @gvegayoncdc

**Comment by gvegayon** [comment]
@AFg6K7h4fhy2 @damonbayer @dylanhmorris @cshelley @SamuelBrand1, we started an issue about this a while ago. We can put this on the J sprint, but ideally, do that once we get #40 done.

**Comment by damonbayer** [comment]
I propose this to be implemented as a new section of the site (like "References" or "Tutorials") called "Developer Documentation"

It should cover things like

- Resources for renewal models
- Links to relevant JAX / NumPyro documentation
- Installation for developers with `poetry install --with dev`
- Explanation of helpful utilities in makefiles that do things like convert quarto documents to python for easier debugging.
- Contributor guidelines (related to https://github.com/CDCgov/multisignal-epi-inference/issues/113)

**Comment by gvegayon** [comment]
Another thing to add ([ref](https://github.com/CDCgov/multisignal-epi-inference/pull/123/#issuecomment-2127695207)): Provide a description and step-by-step of the modules testing. Put special attention to the matplotlib component of pytest.

**Comment by damonbayer** [comment]
Also add instructions for generating docs locally with note of manually modified files

**Comment by AFg6K7h4fhy2** [comment]
Example problem:

```
typos....................................................................Failed
- hook id: typos
- exit code: 2

error: `arange` should be `arrange`
  --> scratch/InfectionSeedingProcess_demo.py:18:15
   |
18 | I0_long = jnp.arange(10)
   |               ^^^^^^
   |
error: `arange` should be `arrange`
  --> model/src/pyrenew/latent/infection_seeding_method.py:185:25
    |
185 |             rate * (jnp.arange(self.n_timepoints) - self.t_pre_seed)
    |                         ^^^^^^
    |

```

Example solution: 

Go to `_typos.toml`. Add `arange = "arange"` under `[default.extend-words]`. 

In the case that words are truly misspelled, then please make changes to these words before pushing your commits.

**Comment by damonbayer** [comment]
Also add guidance for variable naming conventions

**Comment by damonbayer** [comment]
From https://github.com/CDCgov/multisignal-epi-inference/pull/197/files, we could add 
> The structure of the MSR, ignoring the `docs` folder, `__init__.py`s, and image files, can be found via: `tree -I "docs|__init__.py|*.png|*.csv"`.

**Comment by damonbayer** [comment]
There should be a section that outlines how to create a new tutorial.

**Comment by gvegayon** [comment]
This should be taken into consideration: https://github.com/cdcent/cfa-multisignal-renewal/pull/89. Perhaps not 100% related, but it does list dev practices. I suggest porting this and other ADRs to this repo. I think it makes sense.

**Comment by gvegayon** [comment]
Another reference for the document: Quarto RST figures can be a bit tricky. See the following PR: https://github.com/CDCgov/multisignal-epi-inference/pull/110#issue-2286569011. This also showed up in #211.
