### ISSUE TITLE
Standardize admissions nomenclature: use only "hospital admissions", not "hospitalizations"

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/multisignal-epi-inference#75]
## Goal

In the current codebase, both "hospitalizations" and "hospital admissions" are used to refer to incident hospital admissions. The former is ambiguous and can be interpreted as prevalence (number of currently hospitalized individuals) as opposed to incidence (number of new admissions). 

"Hospital admissions" is less ambiguous, and so we should standardize on that.

**Comment by gvegayon** [comment]
Tagging #50 as it should be addressed there.

**Comment by gvegayon** [comment]
Close in favor of #50
