### ISSUE TITLE
Where to doc methods

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#79]
## Discussion

In #73, @AFg6K7h4fhy2 proposes documenting methods as part of the class docstring and the associated method (so double docs). I'm not sure this is the right approach. I like having more info, but it could introduce an extra burden for the dev. So I open this for discussion.

## Context

[[Short paragraph describing how the issue arose and constraints imposed by the existing code architecture]](https://github.com/CDCgov/multisignal-epi-inference/pull/73#discussion_r1562778517)

## Required features

None yet, but it may lead to some refactoring.

**Comment by gvegayon** [comment]
cc @dylanhmorris @natemcintosh this is in your Py dev alley.

**Comment by dylanhmorris** [comment]
We should not reference the methods in the class docstring. Rather, we should give each class method its own docstring and configure [`sphinx.ext.autodoc`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) etc appropriately to make sure the methods are enumerated in the class's rendered documentation. See e.g. [the documentation for the `DataFrame` class in polars](https://docs.pola.rs/py-polars/html/reference/dataframe/index.html) and the corresponding [source code](https://github.com/pola-rs/polars/blob/py-0.20.20/py-polars/polars/dataframe/frame.py)

**Comment by AFg6K7h4fhy2** [comment]
Acknowledging that I have seen this. DHM's suggestion makes sense, somewhat in terms of adhering to [don't repeat yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

Further supporting this is [Numpydocs](https://numpydoc.readthedocs.io/en/latest/format.html) statement (extending to the photo):

> In general, it is not necessary to list class methods. Those that are not part of the public API have names that start with an underscore. In some cases, however, a class may have a great many methods, of which only a few are relevant (e.g., subclasses of ndarray). Then, it becomes useful to have an additional Methods section:

<img width="790" alt="Screenshot 2024-04-16 at 10 11 01" src="https://github.com/CDCgov/multisignal-epi-inference/assets/127630341/0d65ffe0-0729-4bd4-a5ce-57ba9bb72ac5">

**Comment by gvegayon** [comment]
I see. I'm still aligned with @dylanhmorris about where to put the docstring: So, for the moment, let's avoid referencing the method in the class docstring. I'm closing and adding a new issue removing methods documentations for the next sprint.
