### ISSUE TITLE
State-level unadjusted R(t)

### ISSUE THREAD

**Issue by ghost** [CDCgov/multisignal-epi-inference#8]
## Goal

We want to have a single source of truth for the mathematical formulation of the state-level unadjusted $\mathcal{R}^u(t)$ model. We want to be able to use this to immediately code up the math decided upon here. 

## Context

This was discussed in the 2024-02-27 meeting (see [minutes](https://github.com/cdcent/cfa-multisignal-renewal/tree/main/minutes)) and agreed upon in the [ADR record](https://github.com/cdcent/cfa-multisignal-renewal/tree/main/ADR/model) under `model_features.md`. This specific feature should be the same as what's implemented in the existing wastewater model. Completion of this task will allow us to implement the feature more quickly and should facilitate creation of a [model design document](https://github.com/cdcent/cfa-multisignal-renewal/blob/9b69f08e4def65e2a307885036167a0cc3667af7/model/vignettes/model.md). 

## Required features

- [ ] mathematical notation for $\mathcal{R}^u(t)$ alongside associated language 
- [ ] add to the feature to the [model design document ](https://github.com/cdcent/cfa-multisignal-renewal/blob/9b69f08e4def65e2a307885036167a0cc3667af7/model/vignettes/model.md)
- [ ] Include an independent test that checks TBD.
- [ ] Include documentation in the code using docstring

## Out of scope

- This does not include code, just specification of the feature in math/writing

## Related documents

- [Model feature prioritization](https://github.com/cdcent/cfa-multisignal-renewal/discussions/48)
- Existing wastewater [model definition](https://github.com/cdcent/cfa-forecast-renewal-ww/blob/main/model_definition.md)

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/64
author: @kaitejohnson

**Comment by gvegayon** [comment]
To add a little bit more of background information. This should feature the autoregressive Rt with damping (see [here](https://github.com/cdcent/cfa-forecast-renewal-ww/blob/2a59bac72451126e73bc2b1eb87174b93dd95d3c/model_definition.md#instantaneous-reproduction-number)). From the model description in the wastewater project:

> We assume that the unadjusted reproduction number $\mathcal{R}^\mathrm{u}(t)$ is a piecewise-constant function with weekly change points (i.e., if $t$ and $t'$ are days in the same week, then $\mathcal{R}^\mathrm{u}(t)$ = $\mathcal{R}^\mathrm{u}(t')$ ). To account for the dependence of the unadjusted reproduction number in a given week on the previous week, we use a differenced auto-regressive process for the log-scale reproduction number. A log-scale representation is used to ensure that the reproduction number is positive and so that week-to-week changes are multiplicative rather than additive.
> 
> $$
> \log[\mathcal{R}^\mathrm{u}(t_3)] \sim \mathrm{Normal}\left(\log[\mathcal{R}^\mathrm{u}(t_2)] + \beta \left(\log[\mathcal{R}^\mathrm{u}(t_2)] - \log[\mathcal{R}^\mathrm{u}(t_1)]\right), \sigma_r \right)
> $$
>
> where $t_1$, $t_2$, and $t_3$ are days in three successive weeks, $\beta$ is an autoregression coefficient which serves to make week-to-week changes correlated, and $\sigma_r$ determines the overall variation in week-to-week changes. We bound $\beta$ to be between 0 and 1 so that any changes in trend in $\mathcal{R}^\mathrm{u}(t)$ are damped over time to a degree determined by $\beta$.

The feedback component is being addressed in #123.
