### ISSUE TITLE
Refactor nametuples to ease docstrings

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#80]
## Goal

Currently, each namedtuple is declared in a single line, however, this makes documentation somewhat awkward. We need to refactor nametuples to match the class definition as in [here](https://docs.python.org/3/library/typing.html#typing.NamedTuple).

## Context

See https://github.com/CDCgov/multisignal-epi-inference/pull/74/files#r1562868718

## Required features

TBD

## Specifications

TBD

**Comment by AFg6K7h4fhy2** [comment]
Nice catch, I support this, as the current system in place for documenting the namedtuples using `__doc__` is somewhat awkward.
