### ISSUE TITLE
Rendered `pyrenew_demo.md` is out of date with `pyrenew_demo.qmd`

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#81]
It appears that not all of the changes to the `.qmd` file in https://github.com/CDCgov/multisignal-epi-inference/pull/77 made it all the way to the rendered `.md` file. I'm not sure if this was supposed to happen automatically.

**Comment by damonbayer** [comment]
Also note from the diff in that PR that the output is not completely reproducible. The code is the same, but the table and figures are not.

**Comment by gvegayon** [comment]
> It appears that not all of the changes to the `.qmd` file in #77 made it all the way to the rendered `.md` file. I'm not sure if this was supposed to happen automatically.

Not just yet, but that could be the next step!

**Comment by gvegayon** [comment]
> Also note from the diff in #77 that the output is not completely reproducible. The code is the same, but the table and figures are not.

That's right, @damonbayer. Thanks for flagging that. This is important regarding #4 as, besides the tutorial, the tests should work OK. I'll investigate what's the issue here.

**Comment by gvegayon** [comment]
Reproducibility in Python is tricky, especially for figures. #55 added a pytest comparing figures with some tolerance to change. I'm closing this as #4 still will address some of the problems (and the qmd and md files are now synced)
