### ISSUE TITLE
How to handle the poetry.lock file (should we include it?)

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/multisignal-epi-inference#88]
> I wonder if `poetry.lock` should always change with PRs? Or better yet, shouldn't the `pyproject.toml` file be the only thing to distribute with the repo? [poetry doesn't have a black/white stance on it](https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control). I think poetry.lock should only be distributed for development, but not for other users, furthermore, perhaps we should only have poetry.lock for the actual pipeline implementation (not the pipeline package).
> 
> What do you think @AFg6K7h4fhy2 @dylanhmorris @natemcintosh @zsusswein?

_Originally posted by @gvegayon in https://github.com/CDCgov/multisignal-epi-inference/pull/86#discussion_r1572595946_

**Comment by natemcintosh** [comment]
I think using the `poetry.lock` for deploying the code would be good. I am ambivalent about keeping it otherwise
